USE [master]
GO

/****** Object:  Database [SitoSpedizioni]    Script Date: 21/04/2023 22:43:50 ******/
CREATE DATABASE [SitoSpedizioni]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SitoSpedizioni', FILENAME = N'D:\Programmi\MSSQL16.SQLEXPRESS\MSSQL\DATA\SitoSpedizioni.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SitoSpedizioni_log', FILENAME = N'D:\Programmi\MSSQL16.SQLEXPRESS\MSSQL\DATA\SitoSpedizioni_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SitoSpedizioni].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SitoSpedizioni] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET ARITHABORT OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SitoSpedizioni] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SitoSpedizioni] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SitoSpedizioni] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SitoSpedizioni] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SitoSpedizioni] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SitoSpedizioni] SET  MULTI_USER 
GO

ALTER DATABASE [SitoSpedizioni] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SitoSpedizioni] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SitoSpedizioni] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SitoSpedizioni] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SitoSpedizioni] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SitoSpedizioni] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SitoSpedizioni] SET QUERY_STORE = ON
GO

ALTER DATABASE [SitoSpedizioni] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SitoSpedizioni] SET  READ_WRITE 
GO

