// <auto-generated />
namespace PizzeriaWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class m7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m7));
        
        string IMigrationMetadata.Id
        {
            get { return "202305071627560_m7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
